---
- name: Install Packages on Controller Group
  hosts: controller
  become: yes
  
  tasks:
   - name: Install latest version of Apache
     yum:
      name: httpd
      state: latest
      update_cache: yes
